
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.18.0
 * Query Engine version: 34b5a692b7bd79939a9a2c3ef97d816e749cda2f
 */
Prisma.prismaVersion = {
  client: "6.18.0",
  engine: "34b5a692b7bd79939a9a2c3ef97d816e749cda2f"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.ManagerScalarFieldEnum = {
  id: 'id',
  username: 'username',
  password: 'password',
  role: 'role',
  createdAt: 'createdAt'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  userLink: 'userLink',
  phoneNumber: 'phoneNumber',
  email: 'email',
  homeAddress: 'homeAddress',
  leadStatus: 'leadStatus',
  taskImportance: 'taskImportance',
  taskUrgency: 'taskUrgency',
  taskStatus: 'taskStatus',
  legalAction: 'legalAction',
  problemShort: 'problemShort',
  problemFull: 'problemFull',
  nearestTask: 'nearestTask',
  nearestTaskDeadline: 'nearestTaskDeadline',
  timeOfPerformance: 'timeOfPerformance',
  priceSOM: 'priceSOM',
  priceUSD: 'priceUSD',
  courtInfo: 'courtInfo',
  statusInCourt: 'statusInCourt',
  refusalReason: 'refusalReason',
  createdAt: 'createdAt',
  assignmentTime: 'assignmentTime',
  authorId: 'authorId',
  sourceId: 'sourceId',
  opponentId: 'opponentId',
  managerId: 'managerId'
};

exports.Prisma.SourceScalarFieldEnum = {
  id: 'id',
  title: 'title',
  sourceLink: 'sourceLink',
  category: 'category',
  createdAt: 'createdAt',
  authorId: 'authorId'
};

exports.Prisma.OpponentScalarFieldEnum = {
  id: 'id',
  name: 'name',
  link: 'link',
  info: 'info',
  createdAt: 'createdAt'
};

exports.Prisma.BloggerScalarFieldEnum = {
  id: 'id',
  name: 'name',
  link: 'link',
  subscribersCount: 'subscribersCount',
  info: 'info',
  priceSOM: 'priceSOM',
  priceUSD: 'priceUSD',
  phoneNumber: 'phoneNumber',
  email: 'email',
  categories: 'categories',
  createdAt: 'createdAt',
  authorId: 'authorId'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.ROLES = exports.$Enums.ROLES = {
  dev: 'dev',
  owner: 'owner',
  ceo: 'ceo',
  manager: 'manager',
  bot: 'bot'
};

exports.LEAD_STATUS = exports.$Enums.LEAD_STATUS = {
  addedToDB: 'addedToDB',
  messageSent: 'messageSent',
  messageRead: 'messageRead',
  replied: 'replied',
  contactShared: 'contactShared'
};

exports.TASK_IMPORTANCE = exports.$Enums.TASK_IMPORTANCE = {
  one: 'one',
  two: 'two',
  three: 'three'
};

exports.TASK_URGENCY = exports.$Enums.TASK_URGENCY = {
  one: 'one',
  two: 'two',
  three: 'three',
  four: 'four',
  five: 'five'
};

exports.TASK_STATUS = exports.$Enums.TASK_STATUS = {
  notAssigned: 'notAssigned',
  assignedNotStarted: 'assignedNotStarted',
  workInProgress: 'workInProgress',
  blocked: 'blocked',
  checkMe: 'checkMe',
  done: 'done',
  weRefused: 'weRefused',
  leadRefused: 'leadRefused'
};

exports.LEGAL_ACTION = exports.$Enums.LEGAL_ACTION = {
  none: 'none',
  filing: 'filing',
  courtParticipation: 'courtParticipation',
  consultation: 'consultation',
  appointment: 'appointment',
  negotiations: 'negotiations',
  claim: 'claim',
  lawyerRequest: 'lawyerRequest'
};

exports.STATUS_IN_COURT = exports.$Enums.STATUS_IN_COURT = {
  postponed: 'postponed',
  paused: 'paused',
  judgeOnVacation: 'judgeOnVacation',
  reassigned: 'reassigned',
  negotiations: 'negotiations',
  returned: 'returned'
};

exports.REFUSAL_REASON = exports.$Enums.REFUSAL_REASON = {
  none: 'none',
  choseCompetitor: 'choseCompetitor',
  irrelevantServices: 'irrelevantServices',
  tooExpensive: 'tooExpensive',
  noReasonGiven: 'noReasonGiven'
};

exports.SOURCE_CATEGORY = exports.$Enums.SOURCE_CATEGORY = {
  none: 'none',
  realEstate: 'realEstate',
  loans: 'loans',
  other: 'other'
};

exports.Prisma.ModelName = {
  Manager: 'Manager',
  User: 'User',
  Source: 'Source',
  Opponent: 'Opponent',
  Blogger: 'Blogger'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
