
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.18.0
 * Query Engine version: 34b5a692b7bd79939a9a2c3ef97d816e749cda2f
 */
Prisma.prismaVersion = {
  client: "6.18.0",
  engine: "34b5a692b7bd79939a9a2c3ef97d816e749cda2f"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.EmployeeScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  username: 'username',
  password: 'password',
  roles: 'roles'
};

exports.Prisma.PersonScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  name: 'name',
  phoneNumber: 'phoneNumber',
  link: 'link',
  email: 'email',
  homeAddress: 'homeAddress',
  nextDialDate: 'nextDialDate',
  lastDialDate: 'lastDialDate',
  authorId: 'authorId',
  originId: 'originId',
  leadStatus: 'leadStatus'
};

exports.Prisma.CaseScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  caseImportance: 'caseImportance',
  caseUrgency: 'caseUrgency',
  caseStatus: 'caseStatus',
  categories: 'categories',
  problemShort: 'problemShort',
  problemFull: 'problemFull',
  nearestTask: 'nearestTask',
  courtInfo: 'courtInfo',
  nearestTaskDeadline: 'nearestTaskDeadline',
  timeOfPerformance: 'timeOfPerformance',
  assignmentTime: 'assignmentTime',
  nextDialDate: 'nextDialDate',
  lastDialDate: 'lastDialDate',
  refusalReason: 'refusalReason',
  legalAction: 'legalAction',
  statusInCourt: 'statusInCourt',
  priceSOM: 'priceSOM',
  priceUSD: 'priceUSD',
  personId: 'personId',
  authorId: 'authorId',
  opponentId: 'opponentId',
  managerId: 'managerId'
};

exports.Prisma.OriginScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  title: 'title',
  link: 'link',
  categories: 'categories',
  authorId: 'authorId'
};

exports.Prisma.OpponentScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  name: 'name',
  link: 'link',
  info: 'info',
  authorId: 'authorId'
};

exports.Prisma.BloggerScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  name: 'name',
  link: 'link',
  phoneNumber: 'phoneNumber',
  email: 'email',
  info: 'info',
  subscribersCount: 'subscribersCount',
  priceSOM: 'priceSOM',
  priceUSD: 'priceUSD',
  authorId: 'authorId',
  categories: 'categories'
};

exports.Prisma.CallScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  callStatus: 'callStatus',
  info: 'info',
  caseId: 'caseId',
  personId: 'personId',
  authorId: 'authorId'
};

exports.Prisma.AppointmentScalarFieldEnum = {
  id: 'id',
  createAt: 'createAt',
  date: 'date',
  appointmentStatus: 'appointmentStatus',
  caseId: 'caseId',
  personId: 'personId',
  authorId: 'authorId'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.ROLE = exports.$Enums.ROLE = {
  DEV: 'DEV',
  OWNER: 'OWNER',
  CEO: 'CEO',
  SMM_MANAGER: 'SMM_MANAGER',
  SALES_MANAGER: 'SALES_MANAGER',
  ACCOUNT_MANAGER: 'ACCOUNT_MANAGER',
  LAWYER: 'LAWYER',
  BOT: 'BOT'
};

exports.LEAD_STATUS = exports.$Enums.LEAD_STATUS = {
  ADDED_TO_DB: 'ADDED_TO_DB',
  CONTACT_SHARED: 'CONTACT_SHARED',
  CLIENT: 'CLIENT',
  RETURNING_CLIENT: 'RETURNING_CLIENT'
};

exports.IMPORTANCE = exports.$Enums.IMPORTANCE = {
  ONE: 'ONE',
  TWO: 'TWO',
  THREE: 'THREE'
};

exports.URGENCY = exports.$Enums.URGENCY = {
  ONE: 'ONE',
  TWO: 'TWO',
  THREE: 'THREE',
  FOUR: 'FOUR',
  FIVE: 'FIVE'
};

exports.CASE_STATUS = exports.$Enums.CASE_STATUS = {
  UNASSIGNED: 'UNASSIGNED',
  PENDING_START: 'PENDING_START',
  IN_PROGRESS: 'IN_PROGRESS',
  BLOCKED: 'BLOCKED',
  PENDING_CHECK: 'PENDING_CHECK',
  DONE: 'DONE',
  WE_REFUSED: 'WE_REFUSED',
  PERSON_REFUSED: 'PERSON_REFUSED'
};

exports.REFUSAL_REASON = exports.$Enums.REFUSAL_REASON = {
  CHOSE_COMPETITOR: 'CHOSE_COMPETITOR',
  IRRELEVANT_SERVICES: 'IRRELEVANT_SERVICES',
  TOO_EXPENSIVE: 'TOO_EXPENSIVE'
};

exports.LEGAL_ACTION = exports.$Enums.LEGAL_ACTION = {
  CONSULTATION: 'CONSULTATION',
  FILING: 'FILING',
  COURT_PARTICIPATION: 'COURT_PARTICIPATION',
  APPOINTMENT: 'APPOINTMENT',
  NEGOTIATIONS: 'NEGOTIATIONS',
  CLAIM: 'CLAIM',
  LAWYER_REQUEST: 'LAWYER_REQUEST'
};

exports.STATUS_IN_COURT = exports.$Enums.STATUS_IN_COURT = {
  POSTPONED: 'POSTPONED',
  PAUSED: 'PAUSED',
  JUDGE_ON_VACATION: 'JUDGE_ON_VACATION',
  REASSIGNED: 'REASSIGNED',
  NEGOTIATIONS: 'NEGOTIATIONS',
  RETURNED: 'RETURNED'
};

exports.CASE_CATEGORY = exports.$Enums.CASE_CATEGORY = {
  REAL_ESTATE: 'REAL_ESTATE',
  FOREIGNERS: 'FOREIGNERS',
  CARS: 'CARS',
  LOANS: 'LOANS',
  OTHER: 'OTHER'
};

exports.CALL_STATUS = exports.$Enums.CALL_STATUS = {
  DONE: 'DONE',
  MISSED: 'MISSED'
};

exports.APPOINTMENT_STATUS = exports.$Enums.APPOINTMENT_STATUS = {
  DONE: 'DONE',
  MISSED: 'MISSED'
};

exports.Prisma.ModelName = {
  Employee: 'Employee',
  Person: 'Person',
  Case: 'Case',
  Origin: 'Origin',
  Opponent: 'Opponent',
  Blogger: 'Blogger',
  Call: 'Call',
  Appointment: 'Appointment'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
