import { ROUTES } from "@/constants";
import { ROLE } from "@shared/prisma/prisma/client";

export const MAIN_ROUTE_BY_ROLE: Record<ROLE, ROUTES> = {
  [ROLE.DEV]: ROUTES.CASES_LIST,
  [ROLE.OWNER]: ROUTES.CASES_LIST,
  [ROLE.CEO]: ROUTES.CASES_LIST,
  [ROLE.LAWYER]: ROUTES.CASES_LIST,
  [ROLE.SMM_MANAGER]: ROUTES.BLOGGERS_LIST,
  [ROLE.SALES_MANAGER]: ROUTES.ORIGINS_LIST,
  [ROLE.ACCOUNT_MANAGER]: ROUTES.ORIGINS_LIST,

  [ROLE.BOT]: ROUTES.ORIGINS_LIST,
};
